---

- name: add elasticsearch key
  apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  when: ansible_os_family == "Debian"

- name: add elasticsearch repository
  apt_repository: "repo='deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main' state=present update_cache=yes"
  when: ansible_os_family == "Debian"

- name: install elasticsearch
  apt: "pkg=elasticsearch state={{ elasticsearch_state }}"
  when: ansible_os_family == "Debian"

- name: add elasticsearch repository RPM
  template: src=repo.conf.j2 dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"

- name: install elasticsearch RedHat
  yum: pkg=elasticsearch state={{ elasticsearch_state }}
  when: ansible_os_family == "RedHat"

- name: write elasticsearch.yml
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify:
    - restart elasticsearch

- name: write logging.yml
  template: "src={{ elasticsearch_logging_template }} dest=/etc/elasticsearch/logging.yml owner=root group=root mode=0644"
  when: elasticsearch_logging_template is defined and elasticsearch_logging_template|length
  notify:
    - restart elasticsearch

- name: enable elasticsearch service
  service: name: elasticsearch enabled: yes state: started
